### PR TITLE
Rename LICENCE.md to LICENSE.md

### PR DESCRIPTION
**Pull request by dmastag**
Change file name (looks like a Typo)

### CODE REVIEW

**Comment by rnchamberlain** [comment]
In British and Canadian English (and some others) the noun is licence. In US English it is license. For consistency with nodejs/node - and likely other projects - we should perhaps change it.

**Comment by gibfahn** [comment]
I prefer the current spelling. Don't think consistency is massively important here.

**Comment by dmastag** [comment]
I didn't know about the British and Canadian English spelling 😄 

But I think we can agree that if the spelling stays that the link to the License in the README.md needs to be fixed, its currently going to a deadlink

**Comment by rnchamberlain** [comment]
Ah yes, that dead link from the README is a bug, let's rename the file!

**Comment by rnchamberlain** [comment]
Landing this shortly if no objections

**Comment by rnchamberlain** [comment]
Landed as https://github.com/nodejs/node-report/commit/824648730f85b7d434e55382c49f4eef55ce884f

**Pull request closed without merging**
