### PR TITLE
test: Move OS version tests to common.js

### PR DESCRIPTION
**Pull request by richardlau**
See https://github.com/nodejs/node-report/pull/57#issuecomment-280693076.

Moves the OS version tests from a separate test file to `common.js` so it is validated each time a report is validated by a test.

### CODE REVIEW

**Comment by richardlau** [comment]
At some point we might want to break validateContent() into smaller functions (perhaps validateReportHeader, validateSystemInfo, etc.) -- Although this will make totaling the expected number of tests trickier.

**Comment by rnchamberlain** [comment]
LGTM, and I ran a CI on it:
https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/100/
needs a rebase though

**Comment by richardlau** [comment]
Rebased. Started new CI run: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/109/

**Comment by richardlau** [comment]
CI failed on Windows to download a Node runtime. Raised #66.
Also failed on AIX: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/109/MACHINE=aix61-ppc64/console
```
# Subtest: test/test-fatal-error.js
    1..0
not ok 9 - test/test-fatal-error.js # time=30022.646ms
  ---
  timeout: 30000
  file: test/test-fatal-error.js
  failure: timeout
  results:
    ok: false
    count: 0
    pass: 0
    plan:
      start: 1
      end: 0
      skipAll: true
  signal: SIGTERM
  command: >-
    /home/iojs/build/workspace/nodereport-continuous-integration/MACHINE/aix61-ppc64/node-v8.0.0-nightly2017030187a039d721-aix-ppc64/bin/node
  arguments:
    - test/test-fatal-error.js
  ...
```

**Comment by rnchamberlain** [comment]
I think I've seen the AIX failure before. I'd have thought that 30 secs would be plenty of time to fill the 20Mb heap, but maybe the machine is very slow (it does seem to be by far the slowest platform to run in the CI).

**Comment by mhdawson** [comment]
@rnchamberlain if you think there is a flaky test can you open an issue for it so that it gets investigated ?

**Comment by mhdawson** [comment]
I opened an issue for an AIX failure as I ran on master and it there was a failure so it may be persistent as opposed to flaky: https://github.com/nodejs/node-report/issues/69

**Comment by hhellyer** [comment]
LGTM

**Comment by rnchamberlain** [comment]
Landed as https://github.com/nodejs/node-report/commit/918ef913e858fc8c818851f6d0ef1bd59da6306c

**Pull request closed without merging**
