### PR TITLE
docs: update platform support

### PR DESCRIPTION
**Pull request by richardlau**
Add SmartOS to list of supported platforms now that it is being built and tested (#50/#62).

### CODE REVIEW

**Comment by rnchamberlain** [comment]
Landed as https://github.com/nodejs/node-report/commit/cbd267a745c568e4357fc76a0345171ca1a74dc4

**Comment by misterdjules** [comment]
@sam-github Sorry for not responding to your mention, I was on vacation until today.

**Comment by sam-github** [comment]
@misterdjules No problem, I hope you went somewhere sunny! Its been pretty wet and cold lately.

**Pull request closed without merging**
