### PR TITLE
Use nan helpers to set exports

### PR DESCRIPTION
**Pull request by richardlau**
Fixes compilation errors when built on Node.js master with V8 7.4.

Fixes: https://github.com/nodejs/node-report/issues/116

### CODE REVIEW

**Comment by richardlau** [comment]
CI Node.js 6: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/297/
CI Node.js 8: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/298/
CI Node.js 10: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/299/
CI Node.js 11: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/300/
CI Node.js 12: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/301/

**Comment by sam-github** [comment]
Why'd you change the case of the method names?

**Comment by richardlau** [comment]
> 
> 
> Why'd you change the case of the method names?

Because 
```
  exports->Set(Nan::New("triggerReport").ToLocalChecked(),
               Nan::New<v8::FunctionTemplate>(TriggerReport)->GetFunction());
```
exports to JavaScript land a function called `triggerReport` (starting with a lower case) mapping to `TriggerReport` (the C++ method).

The replacement `NAN_EXPORT(target, triggerReport);` exports to JavaScript land a function with the same name as the C++ method so they must match case. Changing the case of the function exposed to JavaScript would be a semver major change (e.g. we document (https://github.com/nodejs/node-report#configuration) requiring 'node-report/api') so I changed the C++ instead.

**Comment by richardlau** [comment]
@sam-github How does the following sound?

> `NAN_EXPORT()` requires the function name exported to JavaScript land and the exported C++ method to match. Change the exported C++ methods to begin with a lower case character to preserve the existing casing of the name exported to JavaScript.

**Comment by sam-github** [comment]
Very clear, thanks.

**Pull request merged**
